name: Build Minimal FFmpeg Windows (ddagrab + scale, auto-fallback)

on:
  push:
    branches:
      - main
  workflow_dispatch:

# You can override this when dispatching the workflow.
env:
  FFMPEG_TAG: n7.0   # if this lacks ddagrab, we auto-fallback to master

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up MSYS2 (MINGW64)
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >
            base-devel git make pkg-config nasm
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-ntldd

      - name: Build x264 and FFmpeg (ddagrab enabled, with fallback)
        shell: msys2 {0}
        run: |
          set -eo pipefail
          JOBS=$(nproc || echo 4)
          ROOT="$PWD"
          BUILD="$ROOT/_build"
          DIST="$ROOT/dist"
          mkdir -p "$BUILD" "$DIST"
          cd "$BUILD"

          echo "==> Build x264 (static, no cli/opencl)"
          if [ ! -d x264 ]; then
            git clone --depth 1 https://code.videolan.org/videolan/x264.git
          fi
          cd x264
          ./configure --enable-static --disable-cli --disable-opencl --prefix="$PWD"
          make -j"$JOBS"
          make install
          export PKG_CONFIG_PATH="$PWD:${PKG_CONFIG_PATH:-}"
          cd ..

          echo "==> Fetch FFmpeg ($FFMPEG_TAG)"
          if [ ! -d FFmpeg ]; then
            git clone --depth 1 -b "$FFMPEG_TAG" https://github.com/FFmpeg/FFmpeg.git
          fi
          cd FFmpeg

          echo "==> Check if this tag has ddagrab; if not, fallback to master"
          if ! ./configure --list-indevs | grep -iq '\bddagrab\b'; then
            echo "No ddagrab in $FFMPEG_TAG; switching to master"
            git fetch origin master --depth=1
            git checkout -f FETCH_HEAD
            ./configure --list-indevs | grep -i '\bddagrab\b'
          fi

          echo "==> Configure FFmpeg (no full-static; add DirectX libs)"
          PKG_CONFIG=/mingw64/bin/pkg-config \
          PKG_CONFIG_PATH="/mingw64/lib/pkgconfig:${PKG_CONFIG_PATH:-}" \
          ./configure \
            --prefix="$DIST" \
            --target-os=mingw32 \
            --arch=x86_64 \
            --enable-static \
            --disable-shared \
            --disable-doc \
            --disable-ffplay \
            --disable-ffprobe \
            --disable-sdl2 \
            --disable-bzlib \
            --disable-iconv \
            --disable-zlib \
            --disable-lzma \
            --disable-autodetect \
            --enable-gpl \
            --enable-libx264 \
            --enable-encoder=libx264 \
            --enable-encoder=aac \
            --enable-indev=dshow \
            --enable-indev=gdigrab \
            --enable-indev=ddagrab \
            --enable-protocol=file \
            --enable-protocol=pipe \
            --enable-muxer=mp4 \
            --enable-muxer=matroska \
            --enable-muxer=mov \
            --enable-filter=scale \
            --extra-libs="-ld3d11 -ldxgi -lole32 -luuid -ldwmapi"

          echo "==> Build"
          make -j"$JOBS"
          make install

          echo "==> Bundle dependent DLLs to make artifact portable"
          cd "$DIST/bin"
          ntldd -R ffmpeg.exe | tr -d '\r' | awk '/mingw64\/bin/ {print $3}' | sort -u | while read -r dll; do
            cp -n "$dll" . || true
          done
          ntldd -R ffprobe.exe | tr -d '\r' | awk '/mingw64\/bin/ {print $3}' | sort -u | while read -r dll; do
            cp -n "$dll" . || true
          done

          echo "==> Post-build sanity"
          ./ffmpeg.exe -hide_banner -devices
          ./ffmpeg.exe -hide_banner -filters | grep -i '^.*scale' || true
          ls -la

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-windows-ddagrab-scale-portable
          path: dist/bin/**
