name: Build static FFmpeg (latest) with x264

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    tags: [ "v*" ]

jobs:
  linux:
    name: Linux (Ubuntu) build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git build-essential pkg-config make \
            yasm nasm autoconf automake libtool

      - name: Build x264 and FFmpeg (static)
        run: |
          set -euxo pipefail
          mkdir -p ffmpeg && cd ffmpeg

          # Sources (latest)
          git clone --depth=1 https://git.ffmpeg.org/ffmpeg.git ffmpeg
          git clone --depth=1 https://code.videolan.org/videolan/x264.git

          # ---- Build x264 (static) ----
          cd x264
          ./configure --enable-static --disable-cli --disable-opencl --prefix=$PWD
          make -j"$(nproc)"
          make install
          # Match your instructions; include lib/pkgconfig for reliability
          export PKG_CONFIG_PATH="$PWD:$PWD/lib/pkgconfig"

          # ---- Build FFmpeg (static) ----
          cd ../ffmpeg
          ./configure \
            --enable-static \
            --enable-gpl \
            --enable-libx264 \
            --disable-ffplay \
            --disable-ffprobe \
            --disable-sdl2 \
            --disable-bzlib \
            --disable-iconv \
            --disable-zlib \
            --disable-lzma
          make -j"$(nproc)"
          ./ffmpeg -version

          # Package
          tar -czf ffmpeg-linux-static.tgz ffmpeg
        shell: bash

      - name: Upload artifact (Linux)
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-linux-static
          path: ffmpeg/ffmpeg/ffmpeg-linux-static.tgz

  macos:
    name: macOS build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          brew update
          brew install yasm nasm pkg-config autoconf automake libtool

      - name: Build x264 and FFmpeg (static, with CoreAudio ldflag)
        run: |
          set -euxo pipefail
          mkdir -p ffmpeg && cd ffmpeg

          # Sources (latest)
          git clone --depth=1 https://git.ffmpeg.org/ffmpeg.git ffmpeg
          git clone --depth=1 https://code.videolan.org/videolan/x264.git

          # ---- Build x264 (static) ----
          cd x264
          ./configure --enable-static --disable-cli --disable-opencl --prefix=$PWD
          make -j"$(sysctl -n hw.logicalcpu)"
          make install
          export PKG_CONFIG_PATH="$PWD:$PWD/lib/pkgconfig"

          # ---- Build FFmpeg (static) ----
          cd ../ffmpeg
          ./configure \
            --enable-static \
            --enable-gpl \
            --enable-libx264 \
            --disable-ffplay \
            --disable-ffprobe \
            --disable-sdl2 \
            --disable-bzlib \
            --disable-iconv \
            --disable-zlib \
            --disable-lzma \
            --extra-ldflags="-framework CoreAudio"
          make -j"$(sysctl -n hw.logicalcpu)"
          ./ffmpeg -version

          # Package
          tar -czf ffmpeg-macos-static.tgz ffmpeg
        shell: bash

      - name: Upload artifact (macOS)
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-macos-static
          path: ffmpeg/ffmpeg/ffmpeg-macos-static.tgz

  windows:
    name: Windows (MSYS2 MinGW64) build
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v4

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            git
            make
            patch
            autoconf
            automake
            libtool
            nasm
            yasm
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-pkg-config

      - name: Build x264 and FFmpeg (static) + apply Windows patch
        run: |
          set -euxo pipefail
          mkdir -p ffmpeg && cd ffmpeg

          # Sources (latest)
          git clone --depth=1 https://git.ffmpeg.org/ffmpeg.git ffmpeg
          git clone --depth=1 https://code.videolan.org/videolan/x264.git

          # Apply Windows patch (expects file in repo at ffmpeg_patches/win/...)
          cd ffmpeg
          if [ -f ../../ffmpeg_patches/win/removed_captureblt_from_gdigrab.patch ]; then
            git apply ../../ffmpeg_patches/win/removed_captureblt_from_gdigrab.patch
          fi
          cd ..

          # ---- Build x264 (static) ----
          cd x264
          ./configure --enable-static --disable-cli --disable-opencl --prefix=$PWD
          make -j"$(nproc)"
          make install
          export PKG_CONFIG_PATH="$PWD:$PWD/lib/pkgconfig"

          # ---- Build FFmpeg (static) ----
          cd ../ffmpeg
          ./configure \
            --enable-static \
            --enable-gpl \
            --enable-libx264 \
            --disable-ffplay \
            --disable-ffprobe \
            --disable-sdl2 \
            --disable-bzlib \
            --disable-iconv \
            --disable-zlib \
            --disable-lzma
          make -j"$(nproc)"
          ./ffmpeg -version || true  # allow running test to fail on non-POSIX

          # Package
          zip -9r ffmpeg-windows-static.zip ffmpeg

      - name: Upload artifact (Windows)
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-windows-static
          path: ffmpeg/ffmpeg/ffmpeg-windows-static.zip
