name: Build Minimal FFmpeg (macOS)

on:
  workflow_dispatch:  # run manually
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Make script executable
        run: chmod +x build_macos_min_ffmpeg.sh

      - name: Run build
        run: ./build_macos_min_ffmpeg.sh

      - name: Upload FFmpeg binary
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-macos-minimal
          path: |
            dist/bin/ffmpeg
            dist/bin/ffprobe
