name: Build Minimal FFmpeg Windows (static, scale only)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up MSYS2 (MINGW64)
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >
            base-devel git make pkg-config nasm
            mingw-w64-x86_64-toolchain

      - name: Build x264 (static) and FFmpeg (static)
        shell: msys2 {0}
        run: |
          set -eo pipefail
          JOBS=$(nproc || echo 4)
          ROOT="$PWD"
          BUILD="$ROOT/_build"
          DIST="$ROOT/dist"
          mkdir -p "$BUILD" "$DIST"
          cd "$BUILD"

          echo "==> Fetching x264"
          if [ ! -d x264 ]; then
            git clone --depth 1 https://code.videolan.org/videolan/x264.git
          fi

          echo "==> Building x264 (static, no cli/opencl)"
          cd x264
          ./configure --enable-static --disable-cli --disable-opencl --prefix="$PWD"
          make -j"$JOBS"
          make install
          export PKG_CONFIG_PATH="$PWD:${PKG_CONFIG_PATH:-}"
          cd ..

          echo "==> Fetching FFmpeg"
          : "${FFMPEG_TAG:=n7.0}"
          if [ ! -d FFmpeg ]; then
            git clone --depth 1 -b "$FFMPEG_TAG" https://github.com/FFmpeg/FFmpeg.git
          fi
          cd FFmpeg

          echo "==> Configure FFmpeg (static, scale filter only)"
          PKG_CONFIG=/mingw64/bin/pkg-config \
          PKG_CONFIG_PATH="/mingw64/lib/pkgconfig:${PKG_CONFIG_PATH:-}" \
          ./configure \
            --prefix="$DIST" \
            --target-os=mingw32 \
            --arch=x86_64 \
            --pkg-config-flags="--static" \
            --extra-cflags="-I/mingw64/include" \
            --extra-ldflags="-static -static-libgcc -static-libstdc++" \
            --enable-static \
            --disable-shared \
            --disable-doc \
            --disable-ffplay \
            --disable-ffprobe \
            --disable-sdl2 \
            --disable-bzlib \
            --disable-iconv \
            --disable-zlib \
            --disable-lzma \
            --disable-autodetect \
            --enable-gpl \
            --enable-libx264 \
            --enable-encoder=libx264 \
            --enable-encoder=aac \
            --enable-indev=dshow \
            --enable-indev=ddagrab \
            --enable-indev=gdigrab \
            --enable-protocol=file \
            --enable-protocol=pipe \
            --enable-muxer=mp4 \
            --enable-muxer=matroska \
            --enable-muxer=mov \
            --enable-filter=scale

          echo "==> Build FFmpeg"
          make -j"$JOBS"
          make install

          echo "==> Contents of dist/bin"
          ls -la "$DIST/bin"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-windows-static-scale
          path: dist/bin/**
