name: Build Minimal FFmpeg Windows (ddagrab + scale)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up MSYS2 (MINGW64)
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >
            base-devel git make pkg-config nasm
            mingw-w64-x86_64-toolchain

      - name: Build x264 and FFmpeg
        shell: msys2 {0}
        run: |
          set -eo pipefail
          JOBS=$(nproc || echo 4)
          ROOT="$PWD"
          BUILD="$ROOT/_build"
          DIST="$ROOT/dist"
          mkdir -p "$BUILD" "$DIST"
          cd "$BUILD"

          echo "==> Build x264"
          if [ ! -d x264 ]; then
            git clone --depth 1 https://code.videolan.org/videolan/x264.git
          fi
          cd x264
          ./configure --enable-static --disable-cli --disable-opencl --prefix="$PWD"
          make -j"$JOBS"
          make install
          export PKG_CONFIG_PATH="$PWD:${PKG_CONFIG_PATH:-}"
          cd ..

          echo "==> Fetch FFmpeg"
          : "${FFMPEG_TAG:=n7.0}"
          if [ ! -d FFmpeg ]; then
            git clone --depth 1 -b "$FFMPEG_TAG" https://github.com/FFmpeg/FFmpeg.git
          fi
          cd FFmpeg

          echo "==> Verify ddagrab is available"
          ./configure --list-indevs | grep -i ddagrab || echo "WARNING: no ddagrab in this tag ($FFMPEG_TAG)"

          echo "==> Configure FFmpeg"
          PKG_CONFIG=/mingw64/bin/pkg-config \
          PKG_CONFIG_PATH="/mingw64/lib/pkgconfig:${PKG_CONFIG_PATH:-}" \
          ./configure \
            --prefix="$DIST" \
            --target-os=mingw32 \
            --arch=x86_64 \
            --enable-static \
            --disable-shared \
            --disable-doc \
            --disable-ffplay \
            --disable-ffprobe \
            --disable-sdl2 \
            --disable-bzlib \
            --disable-iconv \
            --disable-zlib \
            --disable-lzma \
            --disable-autodetect \
            --enable-gpl \
            --enable-libx264 \
            --enable-encoder=libx264 \
            --enable-encoder=aac \
            --enable-indev=dshow \
            --enable-indev=gdigrab \
            --enable-indev=ddagrab \
            --enable-protocol=file \
            --enable-protocol=pipe \
            --enable-muxer=mp4 \
            --enable-muxer=matroska \
            --enable-muxer=mov \
            --enable-filter=scale \
            --extra-libs="-ld3d11 -ldxgi -lole32 -luuid -ldwmapi"

          echo "==> Build"
          make -j"$JOBS"
          make install

          echo "==> Post-build sanity"
          "$DIST/bin/ffmpeg" -hide_banner -devices
          "$DIST/bin/ffmpeg" -hide_banner -filters | grep scale || true

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-windows-ddagrab-scale
          path: dist/bin/**
