windows:
  name: Windows (MSYS2 MinGW64) build (patched first)
  runs-on: windows-latest
  defaults:
    run:
      shell: msys2 {0}
  steps:
    - uses: actions/checkout@v4

    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: >-
          git
          make
          patch
          autoconf
          automake
          libtool
          nasm
          yasm
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-pkg-config
          zip

    - name: Build x264 and FFmpeg (static) + apply Windows patches first
      run: |
        set -euxo pipefail
        mkdir -p ffmpeg && cd ffmpeg

        # Sources (latest)
        git clone --depth=1 https://git.ffmpeg.org/ffmpeg.git ffmpeg
        git clone --depth=1 https://code.videolan.org/videolan/x264.git

        # ---- Apply patches FIRST (Windows-specific, then common) ----
        cd ffmpeg
        apply_patches_dir() {
          local dir="$1"
          if [ -d "$dir" ]; then
            shopt -s nullglob
            for p in "$dir"/*.patch; do
              echo "Applying patch: $p"
              git apply --ignore-whitespace "$p"
            done
          else
            echo "No patch dir: $dir (skipping)"
          fi
        }
        apply_patches_dir ../../ffmpeg_patches/win
        apply_patches_dir ../../ffmpeg_patches/common
        cd ..

        # ---- Build x264 (static) ----
        cd x264
        ./configure --enable-static --disable-cli --disable-opencl --prefix=$PWD
        make -j"$(nproc)"
        make install
        export PKG_CONFIG_PATH="$PWD:$PWD/lib/pkgconfig"

        # ---- Build FFmpeg (static + Windows features) ----
        cd ../ffmpeg
        ./configure \
          --enable-static \
          --enable-gpl \
          --enable-libx264 \
          --enable-ffmpeg \
          --enable-d3d11va \
          --enable-indev=ddagrab \
          --disable-ffplay \
          --disable-ffprobe \
          --disable-sdl2 \
          --disable-bzlib \
          --disable-iconv \
          --disable-zlib \
          --disable-lzma
        make -j"$(nproc)"
        ./ffmpeg -version || true

        # ---- Package (zip the binary) ----
        mkdir -p ../../artifacts/windows
        exe="ffmpeg.exe"
        if [ ! -f "$exe" ]; then exe="ffmpeg_g.exe"; fi
        cp -f "./$exe" ../../artifacts/windows/ffmpeg.exe
        cd ../../artifacts/windows
        zip -9 ffmpeg-windows-static.zip ffmpeg.exe

    - name: Upload artifact (Windows)
      uses: actions/upload-artifact@v4
      with:
        name: ffmpeg-windows-static
        path: artifacts/windows/ffmpeg-windows-static.zip
