name: ffmpeg-min-rec (Windows ddagrab)

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSYS2 (MINGW64)
        uses: msys2/setup-msys2@v2
        with:
          update: true
          msystem: MINGW64
          path-type: minimal
          install: >-
            base-devel
            git
            tar
            patch
            zip
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-binutils
            mingw-w64-x86_64-nasm
            mingw-w64-x86_64-pkgconf
            mingw-w64-x86_64-x264

      - name: Tool sanity check
        shell: msys2 {0}
        run: |
          which gcc || true
          which x86_64-w64-mingw32-gcc || true
          which strip || true
          which x86_64-w64-mingw32-strip || true
          gcc --version | head -n1 || true

      - name: Fetch FFmpeg
        shell: msys2 {0}
        run: |
          git clone --depth=1 https://github.com/FFmpeg/FFmpeg.git ffmpeg
          cd ffmpeg
          git rev-parse --short HEAD > ../FFMPEG_GIT.txt

      - name: Configure (optimized, minimal recording feature set)
        shell: msys2 {0}
        working-directory: ffmpeg
        run: |
          export CC=x86_64-w64-mingw32-gcc
          export CXX=x86_64-w64-mingw32-g++
          export AR=x86_64-w64-mingw32-ar
          export STRIP=x86_64-w64-mingw32-strip

          export CFLAGS="-O3 -pipe -DNDEBUG -fno-math-errno -fno-trapping-math -fomit-frame-pointer -march=x86-64-v3"
          export CXXFLAGS="$CFLAGS"
          export LDFLAGS="-Wl,--as-needed"

          ./configure \
            --target-os=mingw32 \
            --arch=x86_64 \
            --enable-asm --enable-x86asm \
            --enable-lto \
            --disable-debug --disable-doc --disable-ffplay --disable-ffprobe \
            --enable-ffmpeg \
            --disable-everything \
            \
            --enable-avutil --enable-avcodec --enable-avformat --enable-avdevice \
            --enable-swresample --enable-swscale \
            \
            --enable-indev=ddagrab \
            --enable-indev=wasapi \
            \
            --enable-gpl --enable-libx264 --enable-encoder=libx264 \
            --enable-encoder=aac \
            \
            --enable-muxer=matroska \
            --enable-muxer=mp4 \
            --enable-muxer=mov \
            \
            --enable-protocol=file \
            --enable-protocol=pipe \
            \
            --enable-filter=null \
            --enable-filter=anull \
            --enable-filter=fps \
            --enable-filter=scale \
            --enable-filter=format \
            --enable-filter=aformat \
            --enable-filter=aresample \
            --enable-filter=setpts \
            --enable-filter=asetpts

      - name: Build
        shell: msys2 {0}
        working-directory: ffmpeg
        run: |
          make -j"$(nproc)"
          mkdir -p ../artifact/bin
          cp -v ffmpeg.exe ../artifact/bin/

          # Strip if available; otherwise skip gracefully
          if command -v x86_64-w64-mingw32-strip >/dev/null 2>&1; then
            x86_64-w64-mingw32-strip ../artifact/bin/ffmpeg.exe
          elif command -v strip >/dev/null 2>&1; then
            strip ../artifact/bin/ffmpeg.exe
          else
            echo "strip not found; skipping symbol stripping."
          fi

      - name: Package
        shell: bash
        run: |
          pushd artifact
          FFREV=$(cat ../FFMPEG_GIT.txt)
          zip -r "ffmpeg-min-rec_${FFREV}_win64.zip" .
          popd

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-min-rec_win64
          path: artifact/*.zip
