name: ffmpeg-min-rec (Windows ddagrab)

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSYS2 (MINGW64)
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            base-devel
            git
            tar
            patch
            zip
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-nasm
            mingw-w64-x86_64-pkgconf
            mingw-w64-x86_64-ffnvcodec-headers   # NVENC headers (optional but small)
            mingw-w64-x86_64-amf                  # AMD AMF headers (optional but small)
            mingw-w64-x86_64-x264                 # Software H.264 fallback (small & fast)
          msystem: MINGW64
          path-type: minimal

      - name: Fetch FFmpeg
        shell: msys2 {0}
        run: |
          git clone --depth=1 https://github.com/FFmpeg/FFmpeg.git ffmpeg
          cd ffmpeg
          git rev-parse --short HEAD > ../FFMPEG_GIT.txt

      - name: Configure (aggressively optimized, minimal features)
        shell: msys2 {0}
        working-directory: ffmpeg
        run: |
          export CC=x86_64-w64-mingw32-gcc
          export CXX=x86_64-w64-mingw32-g++
          export AR=x86_64-w64-mingw32-ar
          export STRIP=x86_64-w64-mingw32-strip

          # High optimization flags (safe on GitHub runners)
          export CFLAGS="-O3 -pipe -DNDEBUG -fno-math-errno -fno-trapping-math -fomit-frame-pointer -march=x86-64-v3"
          export CXXFLAGS="$CFLAGS"
          export LDFLAGS="-Wl,--as-needed"

          ./configure \
            --target-os=mingw32 \
            --arch=x86_64 \
            --enable-asm --enable-x86asm \
            --enable-lto \
            --disable-debug --disable-doc --disable-ffplay --disable-ffprobe \
            --enable-ffmpeg \
            --disable-everything \
            \
            # Core libs required by minimal pipeline
            --enable-avcodec --enable-avformat --enable-avutil --enable-swresample --enable-swscale --enable-avdevice \
            \
            # Input devices: desktop + audio
            --enable-indev=ddagrab \
            --enable-indev=wasapi \
            \
            # Encoders: prefer HW if present, + tiny SW fallback
            --enable-encoder=h264_nvenc \
            --enable-encoder=hevc_nvenc \
            --enable-encoder=h264_amf \
            --enable-encoder=hevc_amf \
            --enable-libx264 --enable-gpl --enable-encoder=libx264 \
            --enable-encoder=aac \
            \
            # Muxers (recording targets)
            --enable-muxer=matroska \
            --enable-muxer=mp4 \
            --enable-muxer=mov \
            --enable-muxer=flv \
            \
            # Demuxers minimal (rarely used here, but harmless)
            --enable-demuxer=lavfi \
            \
            # Protocols
            --enable-protocol=file \
            --enable-protocol=pipe \
            --enable-protocol=tcp \
            --enable-protocol=udp \
            --enable-protocol=rtp \
            \
            # Filters (keep only what’s commonly needed for recording)
            --enable-filter=null \
            --enable-filter=anull \
            --enable-filter=fps \
            --enable-filter=scale \
            --enable-filter=format \
            --enable-filter=aformat \
            --enable-filter=aresample \
            --enable-filter=setpts \
            --enable-filter=asetpts

      - name: Build
        shell: msys2 {0}
        working-directory: ffmpeg
        run: |
          make -j"$(nproc)"
          mkdir -p ../artifact/bin
          cp -v ffmpeg.exe ../artifact/bin/
          # Strip to reduce size
          x86_64-w64-mingw32-strip ../artifact/bin/ffmpeg.exe

      - name: Package
        shell: bash
        run: |
          pushd artifact
          FFREV=$(cat ../FFMPEG_GIT.txt)
          zip -r "ffmpeg-min-rec_${FFREV}_win64.zip" .
          popd

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-min-rec_win64
          path: artifact/*.zip
